# VacationPy
----

#### Note
* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [1]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os
import json

# Import API key
from api_keys import g_key

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [2]:
cd_weather = pd.read_csv("city_weather.csv")
cd_weather.tail()

,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
554,lethem,3.38,-59.80,78.404,83.0,100.0,1.58,GY,2020-08-18 00:58:26
555,bad wildungen,51.12,9.12,60.800,93.0,20.0,1.69,DE,2020-08-18 00:58:26
556,kudahuvadhoo,2.67,72.89,82.940,66.0,100.0,0.95,MV,2020-08-18 00:58:26
557,bastia,42.67,9.33,77.000,88.0,100.0,1.50,FR,2020-08-18 00:58:26
558,qaqortoq,60.72,-46.03,55.400,58.0,89.0,0.50,GL,2020-08-18 00:58:26

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [3]:
gmaps.configure(api_key=g_key)

In [4]:
# Define Latitude & Longitude as Location
locations = cd_weather[['Lat', 'Lng']].astype(float)

# Humidity as float for weight
humidity = cd_weather['Humidity'].astype(float)

In [5]:
# Create a poverty Heatmap layer
# from https://jupyter-gmaps.readthedocs.io/en/latest/tutorial.html

fig = gmaps.figure(center=(48.0, 0.0), zoom_level=2) 

heat_layer = gmaps.heatmap_layer(
            locations, 
            weights=humidity, 
            max_intensity=100,         
            dissipating=False, 
            point_radius = 1, 
            opacity=1,
            gradient=None
                                ) # Formatting options found by shift tab

fig.add_layer(heat_layer)

plt.savefig("humidityheatmap.png")
fig

Figure(layout=FigureLayout(height='420px'))

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [6]:
#Narrow down the DataFrame to find your ideal weather condition.
#A max temperature lower than 80 degrees but higher than 70.
sub_80 = cd_weather.loc[cd_weather["Max Temp"]<80]
sub_80_70_plus = sub_80.loc[cd_weather["Max Temp"]>70]
sub_80_70_plus_wind = sub_80_70_plus.loc[cd_weather["Wind Speed"]<10]
ideal_weather = sub_80_70_plus_wind.loc[cd_weather["Cloudiness"]==0]
ideal_weather.tail()

,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
460,bowen,-20.02,148.23,78.008,53.0,0.0,4.60,AU,2020-08-18 00:58:09
496,biloela,-24.42,150.50,72.212,30.0,0.0,3.93,AU,2020-08-18 00:58:16
503,jalu,29.03,21.55,79.772,45.0,0.0,4.49,LY,2020-08-18 00:58:17
528,itaituba,-4.28,-55.98,78.980,44.0,0.0,0.24,BR,2020-08-18 00:58:21
539,merauke,-8.47,140.33,79.862,65.0,0.0,4.92,ID,2020-08-18 00:55:05

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [8]:
#Store into variable named hotel_df.
#Add a "Hotel Name" column to the DataFrame.
hotel_df = cd_weather
hotel_df['Hotel Name'] = ""
hotel_df.tail()

,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date,Hotel Name
554,lethem,3.38,-59.80,78.404,83.0,100.0,1.58,GY,2020-08-18 00:58:26,
555,bad wildungen,51.12,9.12,60.800,93.0,20.0,1.69,DE,2020-08-18 00:58:26,
556,kudahuvadhoo,2.67,72.89,82.940,66.0,100.0,0.95,MV,2020-08-18 00:58:26,
557,bastia,42.67,9.33,77.000,88.0,100.0,1.50,FR,2020-08-18 00:58:26,
558,qaqortoq,60.72,-46.03,55.400,58.0,89.0,0.50,GL,2020-08-18 00:58:26,

In [9]:
params = {    
    'radius': 5000,
    'type': 'lodging',
    'key': g_key
}

In [11]:
# Iterate through 
for index, row in hotel_df.iterrows():
    # get lat, lng from df
    lat=row['Lat']
    lng=row['Lng']
    params['location']=f"{lat},{lng}"
    base_url="https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    hotels = requests.get(base_url, params=params).json()
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels['results'][0]['name']
    except (KeyError, IndexError):
        print("Hotel not found. Skippping...")

Hotel not found. Skippping...

In [12]:
hotel_df.head()

,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date,Hotel Name
17,kashan,33.98,51.44,70.484,53.0,0.0,1.17,IR,2020-08-18 00:56:52,Manouchehri Traditional House And Hotel
32,nouadhibou,20.93,-17.03,75.200,69.0,0.0,5.10,MR,2020-08-18 00:56:54,El Medina
37,yeppoon,-23.13,150.73,71.600,49.0,0.0,4.10,AU,2020-08-18 00:56:55,Villa Mar Colina
54,airai,-8.93,125.41,71.024,48.0,0.0,2.30,TL,2020-08-18 00:56:59,Juvinal Martin
84,mizdah,31.45,12.98,77.612,41.0,0.0,2.08,LY,2020-08-18 00:57:08,محمدالمبروك الاريقط

In [14]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
locations = hotel_df[["Lat", "Lng"]]

In [15]:
# Add marker layer ontop of heat map
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig = gmaps.figure()
fig.add_layer(marker_layer)

# Display figure
fig

Figure(layout=FigureLayout(height='420px'))